// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dst
inline double dst(const arma::vec& x, const arma::vec& mu, const arma::mat& Sigma, const double df);
RcppExport SEXP _pldensity_dst(SEXP xSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(dst(x, mu, Sigma, df));
    return rcpp_result_gen;
END_RCPP
}
// dp_normal_mix
Rcpp::List dp_normal_mix(const arma::mat& x, const int N, const double alpha, const arma::vec& lambda, const double kappa, const double nu, const arma::mat& Omega);
RcppExport SEXP _pldensity_dp_normal_mix(SEXP xSEXP, SEXP NSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP kappaSEXP, SEXP nuSEXP, SEXP OmegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< const double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Omega(OmegaSEXP);
    rcpp_result_gen = Rcpp::wrap(dp_normal_mix(x, N, alpha, lambda, kappa, nu, Omega));
    return rcpp_result_gen;
END_RCPP
}
// dp_normal_deval
arma::vec dp_normal_deval(const arma::mat& xnew, const Rcpp::List& dp_normal_mix_model, const int nparticles);
RcppExport SEXP _pldensity_dp_normal_deval(SEXP xnewSEXP, SEXP dp_normal_mix_modelSEXP, SEXP nparticlesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type xnew(xnewSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dp_normal_mix_model(dp_normal_mix_modelSEXP);
    Rcpp::traits::input_parameter< const int >::type nparticles(nparticlesSEXP);
    rcpp_result_gen = Rcpp::wrap(dp_normal_deval(xnew, dp_normal_mix_model, nparticles));
    return rcpp_result_gen;
END_RCPP
}
// marginal
Rcpp::List marginal(const Rcpp::List& dp_normal_mix_model, const arma::uvec dims);
RcppExport SEXP _pldensity_marginal(SEXP dp_normal_mix_modelSEXP, SEXP dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dp_normal_mix_model(dp_normal_mix_modelSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dims(dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(marginal(dp_normal_mix_model, dims));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pldensity_dst", (DL_FUNC) &_pldensity_dst, 4},
    {"_pldensity_dp_normal_mix", (DL_FUNC) &_pldensity_dp_normal_mix, 7},
    {"_pldensity_dp_normal_deval", (DL_FUNC) &_pldensity_dp_normal_deval, 3},
    {"_pldensity_marginal", (DL_FUNC) &_pldensity_marginal, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_pldensity(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
