# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Dirichlet Process Normal Mixture Kernel Density Estimation
#' @description Bla Bla
#' @param x a matrix of observations
#' @param alpha concentration parameter of Dirichlett process
#' @export
dp_normal_mix <- function(x, N, alpha, lambda, kappa, nu, Omega) {
    .Call('_pldensity_dp_normal_mix', PACKAGE = 'pldensity', x, N, alpha, lambda, kappa, nu, Omega)
}

#' @title Eval Point Density
#' @description Bla Bla
#' @export
dp_normal_deval <- function(model, xnew, nparticles = 50L) {
    .Call('_pldensity_dp_normal_deval', PACKAGE = 'pldensity', model, xnew, nparticles)
}

#' @title Take marginals
#' @description Bla Bla
#' @export
dp_normal_marginal <- function(model, dims) {
    .Call('_pldensity_dp_normal_marginal', PACKAGE = 'pldensity', model, dims)
}

#' @title Eval Point Conditional density
#' @description Bla Bla
#' @export
dp_normal_deval_conditional <- function(model, xnew, eval_dims, condition_dims, condition_values, nparticles = 50L) {
    .Call('_pldensity_dp_normal_deval_conditional', PACKAGE = 'pldensity', model, xnew, eval_dims, condition_dims, condition_values, nparticles)
}

