# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Dirichlet Process Normal Mixture Kernel Density Estimation
#' @description Bla Bla
#' @param x a matrix of observations
#' @param alpha concentration parameter of Dirichlett process
#' @export
dp_normal_mix <- function(x, N, alpha, lambda, kappa, nu, Omega) {
    .Call('_pldensity_dp_normal_mix', PACKAGE = 'pldensity', x, N, alpha, lambda, kappa, nu, Omega)
}

#' @title Eval Point Density
#' @description Bla Bla
#' @export
dp_normal_deval <- function(xnew, dp_normal_mix_model) {
    .Call('_pldensity_dp_normal_deval', PACKAGE = 'pldensity', xnew, dp_normal_mix_model)
}

